# GitHub Pages CI/CD workflow
name: ci

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 20

      - run: npm i -g --force corepack@latest && corepack enable

      - name: Install dependencies
        run: cd client && npx nypm@latest i

      - name: Build
        run: cd client && npm run generate

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: client/dist